### ISSUE TITLE
Saving works, but opening doesn't.

### ISSUE THREAD

**Issue by NoMod-Programming** [GRA0007/Blue#7]
It seems that since version 1.0 beta (I don't have any versions before that), saving a project has worked, but opening a project hasn't.
The code for turning an Array to a stack of blocks is [here](https://github.com/GRA0007/Blue/blob/master/src/blocks/BlockIO.as#L53). The code for making a single block out of a block tuple Array is [here](https://github.com/GRA0007/Blue/blob/master/src/blocks/BlockIO.as#L97).
Any help with this issue would be greatly appreciated.

**Comment by NoMod-Programming** [comment]
Also, these three files play a part in the decoding process of a file:
- [ProjectIO](https://github.com/GRA0007/Blue/blob/master/src/util/ProjectIO.as) - This determines which method to open a project with and begins the process of calling functions to decode it
- [JSON](https://github.com/GRA0007/Blue/blob/master/src/util/JSON.as) - This decodes the JSON-formatted blocks into a as3-readable array
- [ZipIO](https://github.com/GRA0007/Blue/blob/master/src/util/ZipIO.as) - This reads the zip files and allows for the JSON to be properly read

**Comment by GRA0007** [comment]
This doesn't work on the latest Scratch 2.0 source either, (https://github.com/LLK/scratch-flash/) nor does it work in scratch's latest version being run on the website now: http://cdn.scratch.mit.edu/scratchr2/static/__b1315cda1358af32fc0764f1bc83910b__/Scratch.swf (if you download the swf). Maybe it's not something within the code because it was never meant to be used offline... I'll try see if I can get the swf from the offline app version of Scratch 2.0.

**Comment by GRA0007** [comment]
Um, here's the code from the offline editor's swf file. Maybe it could help: https://drive.google.com/file/d/0B3uonyYE2l0KZjNxbkg4MTZfWnM/view?usp=sharing

**Comment by NoMod-Programming** [comment]
A quick search on scratch gave me this. It might be a local issue with the computer, then:
[https://scratch.mit.edu/discuss/topic/40220/](https://scratch.mit.edu/discuss/topic/40220/)

**Comment by NoMod-Programming** [comment]
Alright, it seems that chrome's stupid PPAPI flash is the culprit. Just use safari or another browser for testing :(
